
public enum TokenType {
	FEATURE, IS, END,DO, IF, THEN, ELSE, IDENT, PRINT, FROM, UNTIL, LOOP, INT_LIT, ASSIGNMENT_OPERATOR, LE_OPERATOR, LT_OPERATOR, GE_OPERATOR, GT_OPERATOR,
		EQ_OPERATOR, NE_OPERATOR, ADD_OPERATOR, SUB_OPERATOR, MUL_OPERATOR, DIV_OPERATOR,
		LEFT_PAREN, RIGHT_PAREN;
}